version: '3'

services:

  tomcat-dev:
    build: .
    ports:
      - "8080:8080"

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
